### PR TITLE
whoa's update

### PR DESCRIPTION
**Pull request by aapokaapo**
Added listeners: Disconnect, Flag_Grab, Flag_Drop, Round_End, Gamemode
Modified listener: Elim - listens to suicides now too ( *Player killed himself with a paintgren)
Cleaned regex

### CODE REVIEW

**Comment by mRokita** [comment]
Nice! :)

**Comment by aapokaapo** [comment]
review this one please :)

**Comment by mRokita** [comment]
I will do that for sure, give me a few weeks - im a bit busy right now

**Comment by aapokaapo** [comment]
There's one major bug I don't know how to fix: timeouts. It's probably the sent rcon's that don't get response and timeout and then the whole script crashes...

**Review by mRokita — APPROVED** [review]
Nice work!

**Comment by aapokaapo** [comment]
Now that i think about it, suicides should probably be its own function.

**Pull request merged**
